---
- name: Add repository for IUS 6
  yum: name=https://dl.iuscommunity.org/pub/ius/stable/CentOS/6/x86_64/ius-release-1.0-14.ius.centos6.noarch.rpm state=present
  when: ansible_distribution_major_version == "6"  and ansible_os_family == "RedHat"

- name: add repository for IUS 7
  yum: name=https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm state=present
  when: ansible_distribution_major_version == "7" and ansible_os_family == "RedHat"
#- name: ensure that ius archive is enable
#  lineinfile: 
#        dest: /etc/yum.repos.d/ius-archive.repo 
#        regexp: '^enabled=0$'
#        line: 'enable=1' 
#        state: present
