- name: Ensure Varnish dependencies are installed.
  yum: name={{ item }} state=present
  with_items:
    - yum-utils
    - pygpgme

- name: Set the packagecloud repository name based on the version.
  set_fact:
    varnish_packagecloud_repo: "varnish{{ varnish_version|replace('.', '') }}"

- name: Add Varnish packagecloud.io yum repo.
  yum_repository:
    name: varnishcache_{{ varnish_packagecloud_repo }}
    description: Varnish Cache packagecloud.io repository.
    baseurl: https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/el/{{ ansible_distribution_major_version|int }}/$basearch
    repo_gpgcheck: no
    gpgcheck: no
    enabled: yes
    gpgkey: https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/gpgkey
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
  register: varnish_packagecloud_repo_addition

- name: Refresh yum metadata cache if repo changed.
  command: >
    yum clean metadata
    warn=no

- name: install varnish 
  yum: name="{{ varnish_package_name }}" state=present

- name: Copy Varnish sysconfig.
  template: src=varnish.j2 dest=/etc/sysconfig/varnish owner=root group=root mode=0644

- name: Create directory for log
  file: path="{{varnishncsa_path_log}}" state=directory

- name: Copy Varnishncsa init script.
  template: src=varnishncsa.j2 dest=/etc/init.d/varnishncsa owner=root group=root 
  when: ansible_distribution_major_version == "6"
  notify: restart varnishncsa

- name: Copy Varnishlog init script.
  template: src=varnishlog.j2 dest=/etc/init.d/varnishlog owner=root group=root 
  when: ansible_distribution_major_version == "6"

- name: Copy Varnish default VCL.
  template: src={{  varnish_vcl_file }}.j2   dest={{ varnish_config_path }}/default.vcl  owner=root group=root mode=644 
  notify: restart varnish

- name: Ensure Varnish that to run on startup.
  service: name=varnish  enabled=yes

