
- name: copy vhost in nginx
  template: src=vhost_nginx.j2 dest=/etc/nginx/sites-available/{{ ngx_default_server_name }} 
  notify: Reload Nginx
  tags: vhost_api
  when: nginx is defined

- name: activate  vhost in nginx
  file: src="/etc/nginx/sites-available/{{ ngx_default_server_name }}" dest="/etc/nginx/sites-enabled/{{ ngx_default_server_name }}" state=link
  notify: Reload Nginx
  tags: vhost_api
  when: nginx is defined

